version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: task-management-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanagement
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # You can add your Node.js API service here later
  # api:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/taskmanagement?schema=public
  #     JWT_SECRET: your-secret-key-replace-this-in-production
  #     PORT: 3000

volumes:
  postgres_data:
